# Generated by Django 4.1.1 on 2023-02-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="games",
            name="is_released",
            field=models.BooleanField(default=False),
        ),
    ]
