# Generated by Django 4.1.1 on 2023-02-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0002_games_is_released"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_released",
            field=models.BooleanField(default=False),
        ),
    ]
