# Generated by Django 4.1.1 on 2023-02-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0004_alter_date_has_games_alter_date_has_movies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="genres_list",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
